import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { getSiteConfig, getHeaderData, getFooterData } from "../lib/cms";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch global data once at the layout level
  const [siteConfig, headerData, footerData] = await Promise.all([
    getSiteConfig(),
    getHeaderData(),
    getFooterData(),
  ]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header siteConfig={siteConfig} headerData={headerData} />
        <main>{children}</main>
        <Footer footerData={footerData} />
      </body>
    </html>
  );
}
