name: Trigger Vercel Production Deploy

on:
  workflow_run:
    workflows: ["Contentful Switch Master Alias"]
    types: [completed]

jobs:
  trigger-vercel-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].base.ref == 'main' }}
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Trigger Vercel deploy hook
        id: deploy
        env:
          VERCEL_PRODUCTION_DEPLOY_HOOK: ${{ secrets.VERCEL_PRODUCTION_DEPLOY_HOOK }}
        run: |
          if [ -z "${VERCEL_PRODUCTION_DEPLOY_HOOK}" ]; then
            echo "VERCEL_PRODUCTION_DEPLOY_HOOK is not set" >&2
            exit 1
          fi
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${VERCEL_PRODUCTION_DEPLOY_HOOK}")
          echo "HTTP status: ${STATUS}"
          echo "status=${STATUS}" >> $GITHUB_OUTPUT
          if [ "${STATUS}" -ge 200 ] && [ "${STATUS}" -lt 300 ]; then
            echo "Vercel deploy hook triggered successfully."
          else
            echo "Failed to trigger Vercel deploy hook (status ${STATUS})." >&2
            exit 1
          fi

      - name: Comment PR with deployment trigger
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.workflow_run.pull_requests?.[0];
            if (!pr?.number) {
              core.setFailed('No pull request found on workflow_run payload.');
              return;
            }
            const status = '${{ steps.deploy.outputs.status }}';
            const body = `## 🚀 Vercel Production Deploy Triggered\n\n` +
              `Deployment hook called for master site.\n\n` +
              `**HTTP status**: \`${status || 'unknown'}\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
